services:
 backend:
   image: YOUR_DOCKER_HUB_USERNAME/chat-backend:latest
   build:
     context: ./backend # Path to the backend Dockerfile
   ports:
     - "8080:8080"
   platform: linux/amd64


 backend2:
   image: YOUR_DOCKER_HUB_USERNAME/chat-backend-2:latest
   build:
     context: ./backend # Path to the backend Dockerfile
   ports:
     - "8081:8080"
   platform: linux/amd64


 auth-backend:
   image: YOUR_DOCKER_HUB_USERNAME/auth-backend:latest
   build:
     context: ./auth-backend # Path to the backend Dockerfile
   ports:
     - "5001:5001" 
   platform: linux/amd64


 frontend:
   image: YOUR_DOCKER_HUB_USERNAME/chat-client:latest
   build:
     context: ./frontend/hhld-chat-fe # Path to the frontend Dockerfile
   ports:
     - "3000:3000"
   depends_on:
     - backend # Wait for backend service to be ready before starting frontend
   platform: linux/amd64


 frontend2:
   image: YOUR_DOCKER_HUB_USERNAME/chat-client-2:latest
   build:
     context: ./frontend/hhld-chat-fe-2 # Path to the frontend Dockerfile
   ports:
     - "3001:3000"
   depends_on:
     - backend # Wait for backend service to be ready before starting frontend
   platform: linux/amd64
